# Generated by Django 4.1.3 on 2022-12-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_category_product_image_product_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("contact_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(default="", max_length=60)),
                ("phone", models.IntegerField(default="", max_length=10)),
                ("message", models.CharField(default="", max_length=1000)),
            ],
        ),
    ]
