# Generated by Django 4.1.3 on 2022-12-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("items_json", models.CharField(max_length=5000)),
                ("name", models.CharField(max_length=500)),
                ("email", models.CharField(max_length=500)),
                ("phone", models.IntegerField(max_length=10)),
                ("address", models.CharField(max_length=500)),
                ("state", models.CharField(max_length=500)),
                ("zip_code", models.CharField(max_length=500)),
            ],
        ),
    ]
