# Generated by Django 4.1.3 on 2022-12-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
    ]
