# Generated by Django 4.1.3 on 2022-12-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_orders_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="address",
            field=models.CharField(max_length=5009),
        ),
    ]
