# Generated by Django 4.1.3 on 2022-12-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_orders_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.IntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="orders",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orders",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
