# Generated by Django 4.1.3 on 2022-12-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_contact_phone_alter_orders_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="items_json",
            field=models.CharField(default="", max_length=5000),
        ),
    ]
